In [16]:
import pandas as pd

In [29]:
df1 = pd.read_csv("../data/teletrabajo_2022septiembre_limpia.csv", dtype={"ruc_empresa":str})

In [30]:
df2 = pd.read_csv("../data/ruc_info_cleaning.csv", dtype={"numeroRuc":str})

In [31]:
df = df1.merge(df2, how='inner', left_on="ruc_empresa", right_on="numeroRuc")

In [32]:
ruc_prueba='0190055965001'

In [33]:
df1[df1.ruc_empresa==ruc_prueba]

,motivo_teletrabajo,genero,provincia_contrato,provincia_contrato (grupo),finalizado,contratos,anio_fecha_inicio_teletrabajo,anio_fecha_inicio_teletrabajo (grupo),canton_contrato,estado_teletrabajo,fecha_consulta,mes_fecha_inicio_teletrabajo,modo_ejecucion,Número de registros,ruc_empresa
63,Emergente,Femenino,AZUAY,AZUAY,Vigente,42,2020,Otro,CUENCA,Activo,2022-11-10 04:58:36,Marzo,Teletrabajo,1,0190055965001
435,Emergente,Femenino,EL ORO,EL ORO,Vigente,3,2020,Otro,MACHALA,Activo,2022-11-10 04:58:36,Marzo,Teletrabajo,1,0190055965001
556,Emergente,Femenino,ESMERALDAS,ESMERALDAS,Vigente,1,2020,Otro,ESMERALDAS,Activo,2022-11-10 04:58:36,Marzo,Teletrabajo,1,0190055965001
651,Emergente,Femenino,GUAYAS,GUAYAS,Vigente,4,2020,Otro,GUAYAQUIL,Activo,2022-11-10 04:58:36,Marzo,Teletrabajo,1,0190055965001
1736,Emergente,Femenino,IMBABURA,IMBABURA,Vigente,1,2020,Otro,IBARRA,Activo,2022-11-10 04:58:36,Marzo,Teletrabajo,1,0190055965001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37565,Emergente,Masculino,AZUAY,AZUAY,Finalizado,3,2020,Otro,CUENCA,Activo,2022-11-10 04:58:36,Noviembre,Teletrabajo,1,0190055965001
37685,Emergente,Masculino,AZUAY,AZUAY,Finalizado,2,2020,Otro,CUENCA,Activo,2022-11-10 04:58:36,Diciembre,Teletrabajo,1,0190055965001
37792,Emergente,Masculino,AZUAY,AZUAY,Finalizado,4,2021,Otro,CUENCA,Activo,2022-11-10 04:58:36,Enero,Teletrabajo,1,0190055965001
37982,Emergente,Masculino,AZUAY,AZUAY,Finalizado,1,2021,Otro,CUENCA,Activo,2022-11-10 04:58:36,Febrero,Teletrabajo,1,0190055965001
38192,Emergente,Masculino,AZUAY,AZUAY,Finalizado,3,2021,Otro,CUENCA,Activo,2022-11-10 04:58:36,Abril,Teletrabajo,1,0190055965001

In [34]:
df2[df2.numeroRuc==ruc_prueba]

,numeroRuc,razonSocial,estadoPersonaNatural,estadoSociedad,claseContribuyente,obligado,actividadContribuyente,representanteLegal,agenteRepresentante,personaSociedad,subtipoContribuyente,motivoCancelacion,motivoSuspension,fechaInicioActividad,fechaCese,fechaInscripcion,fechaActualizacion
53,0190055965001,BANCO DEL AUSTRO S. A,NaN,ACT,ESPECIAL,S,ACTIVIDADES DE INTERMEDIACIÓN MONETARIA REALIZ...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11

In [35]:
df[df.ruc_empresa=='0190055965001']

,motivo_teletrabajo,genero,provincia_contrato,provincia_contrato (grupo),finalizado,contratos,anio_fecha_inicio_teletrabajo,anio_fecha_inicio_teletrabajo (grupo),canton_contrato,estado_teletrabajo,...,representanteLegal,agenteRepresentante,personaSociedad,subtipoContribuyente,motivoCancelacion,motivoSuspension,fechaInicioActividad,fechaCese,fechaInscripcion,fechaActualizacion
840,Emergente,Femenino,AZUAY,AZUAY,Vigente,42,2020,Otro,CUENCA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
841,Emergente,Femenino,EL ORO,EL ORO,Vigente,3,2020,Otro,MACHALA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
842,Emergente,Femenino,ESMERALDAS,ESMERALDAS,Vigente,1,2020,Otro,ESMERALDAS,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
843,Emergente,Femenino,GUAYAS,GUAYAS,Vigente,4,2020,Otro,GUAYAQUIL,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
844,Emergente,Femenino,IMBABURA,IMBABURA,Vigente,1,2020,Otro,IBARRA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,Emergente,Masculino,AZUAY,AZUAY,Finalizado,3,2020,Otro,CUENCA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
949,Emergente,Masculino,AZUAY,AZUAY,Finalizado,2,2020,Otro,CUENCA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
950,Emergente,Masculino,AZUAY,AZUAY,Finalizado,4,2021,Otro,CUENCA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
951,Emergente,Masculino,AZUAY,AZUAY,Finalizado,1,2021,Otro,CUENCA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11
952,Emergente,Masculino,AZUAY,AZUAY,Finalizado,3,2021,Otro,CUENCA,Activo,...,0101292977,TALBOT DUEÑAS JAIME GUILLERMO,SCD,BAJO CONTROL DE LA SUPERINTENDENCIA DE BANCOS,NaN,NaN,1977-08-02,NaN,NaN,2022-11-11

In [38]:
df3 = pd.read_csv("../data/super_cias_filtered.csv", dtype={"RUC":str})

In [39]:
df3 = df3.rename(index=str, columns={"PAÍS": "PAÍS_CIA", "REGIÓN": "REGIÓN_CIA", "CANTÓN": "CANTÓN_CIA", "CIUDAD":"CIUDAD_NEW"})

In [40]:
df3.drop(['No. FILA'], axis=1, inplace=True)

In [41]:
df3.dtypes

EXPEDIENTE             int64
RUC                   object
NOMBRE                object
SITUACIÓN LEGAL       object
FECHA_CONSTITUCION    object
TIPO                  object
PAÍS_CIA              object
REGIÓN_CIA            object
PROVINCIA             object
CANTÓN_CIA            object
CIUDAD_NEW            object
REPRESENTANTE         object
CAPITAL SUSCRITO      object
dtype: object

In [42]:
df3['RUC'] = df3['RUC'].apply(str)

In [46]:
df3.R

,EXPEDIENTE,RUC,NOMBRE,SITUACIÓN LEGAL,FECHA_CONSTITUCION,TIPO,PAÍS_CIA,REGIÓN_CIA,PROVINCIA,CANTÓN_CIA,CIUDAD_NEW,REPRESENTANTE,CAPITAL SUSCRITO
0,2,1790004724001,ACERIA DEL ECUADOR CA ADELCA.,ACTIVA,17/12/1963,ANÓNIMA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,JXFA E.U.R.L.,"72.500.000,00"
1,63,1790084604001,CONFITECA C.A.,ACTIVA,21/10/1963,ANÓNIMA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,MONTERO AGUIRRE SEBASTIAN JORGE,"15.865.800,00"
2,78,1790027740001,ASTAP CIA LTDA,ACTIVA,02/02/1955,RESPONSABILIDAD LIMITADA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,RODRIGUEZ YANEZ MARCO ANTONIO,"250.000,00"
3,83,1890000130001,ASSA-AUTOMOTORES DE LA SIERRA S.A.,ACTIVA,29/06/1960,ANÓNIMA,ECUADOR,SIERRA,TUNGURAHUA,AMBATO,AMBATO,SEVILLA GORTAIRE SANTIAGO MARTIN,"18.400.000,00"
4,85,1790014797001,AUTOMOTORES Y ANEXOS S.A. (A.Y.A.S.A.),ACTIVA,30/04/1963,ANÓNIMA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,MALO ALVAREZ LEONARDO GIL,"22.327.505,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7424,743701,0993371717001,EQ-PAY S.A.S.,ACTIVA,20/04/2022,SOCIEDAD POR ACCIONES SIMPLIFICADA,ECUADOR,COSTA,GUAYAS,GUAYAQUIL,GUAYAQUIL,VARGAS ROMERO MANUEL DE JESUS,"5.000,00"
7425,743744,0993372003001,POCHTECA ECUADOR S.A.S.,ACTIVA,21/04/2022,SOCIEDAD POR ACCIONES SIMPLIFICADA,ECUADOR,COSTA,GUAYAS,GUAYAQUIL,GUAYAQUIL,REPRESENTACIÓN Y ASESORÍA FEREP CIA.LTDA.,"800,00"
7426,743808,1793195901001,FANTASTICA ATL S.A.S.,ACTIVA,26/04/2022,SOCIEDAD POR ACCIONES SIMPLIFICADA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,PALACIO QUIÑONES MARCEL ANDRES,"400,00"
7427,744876,1793197141001,ACCIONECORP S.A.S.,ACTIVA,16/06/2022,SOCIEDAD POR ACCIONES SIMPLIFICADA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,HURTADO ARGUELLO JOSUE ADRIAN,"2.000,00"
7428,745331,1793198363001,SERVICIOS Y REPRESENTACIONES GA GASERV S.A.S.,ACTIVA,16/07/2022,SOCIEDAD POR ACCIONES SIMPLIFICADA,ECUADOR,SIERRA,PICHINCHA,QUITO,QUITO,MORA VALLEJO MARIA EUGENIA,"1.000,00"

In [44]:
df = df.merge(df3, how='inner', left_on="ruc_empresa", right_on="RUC")
df.ruc_empresa

0        1792040825001
1        1792040825001
2        1792040825001
3        1792040825001
4        1792040825001
             ...
28124    0992169362001
28125    1391924127001
28126    0190473767001
28127    1792931142001
28128    0993371717001
Name: ruc_empresa, Length: 28129, dtype: object

In [52]:
df[["ruc_empresa", "numeroRuc"]]

         ruc_empresa      numeroRuc
0      1792040825001  1792040825001
1      1792040825001  1792040825001
2      1792040825001  1792040825001
3      1792040825001  1792040825001
4      1792040825001  1792040825001
...              ...            ...
28124  0992169362001  0992169362001
28125  1391924127001  1391924127001
28126  0190473767001  0190473767001
28127  1792931142001  1792931142001
28128  0993371717001  0993371717001

[28129 rows x 2 columns]

In [54]:
df.columns

Index(['motivo_teletrabajo', 'genero', 'provincia_contrato',
       'provincia_contrato (grupo)', 'finalizado', 'contratos',
       'anio_fecha_inicio_teletrabajo',
       'anio_fecha_inicio_teletrabajo (grupo)', 'canton_contrato',
       'estado_teletrabajo', 'fecha_consulta', 'mes_fecha_inicio_teletrabajo',
       'modo_ejecucion', 'Número de registros', 'ruc_empresa', 'numeroRuc',
       'razonSocial', 'estadoPersonaNatural', 'estadoSociedad',
       'claseContribuyente', 'obligado', 'actividadContribuyente',
       'representanteLegal', 'agenteRepresentante', 'personaSociedad',
       'subtipoContribuyente', 'motivoCancelacion', 'motivoSuspension',
       'fechaInicioActividad', 'fechaCese', 'fechaInscripcion',
       'fechaActualizacion', 'EXPEDIENTE_x', 'RUC_x', 'NOMBRE_x',
       'SITUACIÓN LEGAL_x', 'FECHA_CONSTITUCION_x', 'TIPO_x', 'PAÍS_CIA_x',
       'REGIÓN_CIA_x', 'PROVINCIA_x', 'CANTÓN_CIA_x', 'CIUDAD_NEW_x',
       'REPRESENTANTE_x', 'CAPITAL SUSCRITO_x', 'EXPEDIENTE_y', 'RUC_y',
       'NOMBRE_y', 'SITUACIÓN LEGAL_y', 'FECHA_CONSTITUCION_y', 'TIPO_y',
       'PAÍS_CIA_y', 'REGIÓN_CIA_y', 'PROVINCIA_y', 'CANTÓN_CIA_y',
       'CIUDAD_NEW_y', 'REPRESENTANTE_y', 'CAPITAL SUSCRITO_y'],
      dtype='object')

In [57]:
df.isnull().sum()

motivo_teletrabajo                           0
genero                                       0
provincia_contrato                           0
provincia_contrato (grupo)                   0
finalizado                                   0
contratos                                    0
anio_fecha_inicio_teletrabajo                0
anio_fecha_inicio_teletrabajo (grupo)        0
canton_contrato                              0
estado_teletrabajo                           0
fecha_consulta                               0
mes_fecha_inicio_teletrabajo                 0
modo_ejecucion                               0
Número de registros                          0
ruc_empresa                                  0
razonSocial                                  0
estadoSociedad                               0
claseContribuyente                           0
obligado                                     0
actividadContribuyente                       0
representanteLegal                           0
agenteRepresentante                          0
personaSociedad                              0
subtipoContribuyente                         0
motivoCancelacion                        28055
motivoSuspension                         26303
fechaInicioActividad                         0
fechaCese                                28078
fechaInscripcion                         27863
fechaActualizacion                         377
EXPEDIENTE_x                                 0
RUC_x                                        0
NOMBRE_x                                     0
SITUACIÓN LEGAL_x                            0
FECHA_CONSTITUCION_x                         0
TIPO_x                                       0
PAÍS_CIA_x                                   0
REGIÓN_CIA_x                                 0
PROVINCIA_x                                  0
CANTÓN_CIA_x                                 0
CIUDAD_NEW_x                                 0
REPRESENTANTE_x                              0
CAPITAL SUSCRITO_x                           0
EXPEDIENTE_y                                 0
RUC_y                                        0
NOMBRE_y                                     0
SITUACIÓN LEGAL_y                            0
FECHA_CONSTITUCION_y                         0
TIPO_y                                       0
PAÍS_CIA_y                                   0
REGIÓN_CIA_y                                 0
PROVINCIA_y                                  0
CANTÓN_CIA_y                                 0
CIUDAD_NEW_y                                 0
REPRESENTANTE_y                              0
CAPITAL SUSCRITO_y                           0
dtype: int64

In [58]:
df.drop(['numeroRuc','estadoPersonaNatural'], axis=1, inplace=True)

KeyError: "['numeroRuc' 'estadoPersonaNatural'] not found in axis"

In [60]:
df.drop(['motivoCancelacion'], axis=1, inplace=True)

In [64]:
df_sum_null=pd.DataFrame(df.isnull().sum())
df_sum_null=df_sum_null[df_sum_null[0]>0]
df_sum_null

                        0
motivoSuspension    26303
fechaCese           28078
fechaInscripcion    27863
fechaActualizacion    377

In [65]:
df.drop(['motivoSuspension','fechaCese','fechaInscripcion'], axis=1, inplace=True)

In [68]:
df=df[~df.fechaActualizacion.isnull()]

In [73]:
df.iloc[:,:].to_csv("../data/teletrabajo_ec.csv",index=False)

In [ ]:
df